version: '3.8'

services:
  apollon_standalone:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: apollon_standalone
    environment:
      - DEPLOYMENT_URL=${DEPLOYMENT_URL}
    restart: always
    networks:
      - apollon_network
    ports:
      - "8080:8080"

volumes: {}

networks:
  apollon_network:
    driver: bridge
